apps/datos/urls.py
from django.urls import path
from . import views

app_name = 'bicho_app'

urlpatterns = [
    path('', views.InicioView.as_view()),
    path('listar-todo-bichos', views.ListAllPokemon.as_view(), name='bichosall'),
    path('listar-region/<zona>', views.ListaRegion.as_view()),
    path('listar-por-region/', views.ListaRegionByKword.as_view()),
    path('datos-bicho/<pk>', views.DatosPokemon.as_view(), name='detallebicho'),
    path('success', views.SuccessView.as_view(), name='correcto'),
    path('agregar-pokemon', views.CrearPokemon.as_view(), name='agregarbicho'),
    path('modificar-pokemon/<pk>', views.ModificarBicho.as_view(), name='modificar_bicho'),
    path('borrar-pokemon/<pk>', views.BorrarPokemon.as_view(), name='eliminar_bicho')


]

pokemon/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
       re_path('bichos/', include('apps.datos.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/datos/models.py
from django.db import models

# Create your models here.

class Region(models.Model):
    name = models.CharField('Región', max_length=30)

    class Meta:
        verbose_name = 'Región'
        verbose_name_plural = 'Regiones'
        ordering = ['name']
        unique_together = ('name',)
    
    def __str__(self):
        return self.name

class Tipo(models.Model):
    name = models.CharField('Tipos', max_length=30)

    class Meta:
        verbose_name = 'Tipo'
        verbose_name_plural = 'Tipos'
        ordering = ['name']
        unique_together = ('name',)
    
    def __str__(self):
        return self.name

class Pokemon(models.Model):
    name = models.CharField('Nombre', max_length=30)
    pc = models.IntegerField('PC')
    ps = models.IntegerField('PS')
    region = models.ForeignKey(Region, on_delete = models.CASCADE)
    tipos = models.ManyToManyField(Tipo)
    avatar = models.ImageField(upload_to = 'pokemon', blank = True, null = True)

    class Meta:
        verbose_name = 'Pokemon'
        verbose_name_plural = 'Bichos'
        ordering = ['name']
        unique_together = ('name',)
    
    def __str__(self):
        return self.name

apps/datos/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Region, Tipo, Pokemon

class InicioView(TemplateView):
	template_name = 'inicio.html'

class ListAllPokemon(ListView):
	template_name = 'bichos/lista-nueva-todos.html'
	paginate_by = 10
	ordering = "-id"
	model = Pokemon


class ListaRegion(ListView):
	template_name = 'bichos/lista_region.html'

	def get_queryset(self):
		zona = self.kwargs['zona']
		lista = Pokemon.objects.filter(region__name = zona)
		return lista


class ListaRegionByKword(ListView):
	template_name = 'bichos/by_kword.html'
	context_object_name = 'bichos'

	def get_queryset(self):
		nombre_region_buscada = self.request.GET.get("nombre_cargado_usuario",)
		return Pokemon.objects.filter(region__name = nombre_region_buscada)


class DatosPokemon(DetailView):
	model = Pokemon
	template_name = 'bichos/detalle-pokemon.html'

	def get_context_data(self, **kwargs):
		context = super(DatosPokemon, self).get_context_data(**kwargs)
		return context

class SuccessView(TemplateView):
	template_name = "bichos/success.html"

class CrearPokemon(CreateView):
	model = Pokemon
	template_name = 'bichos/agregar.html'
	fields = [
		'name',
		'pc',
		'ps',
		'region',
		'tipos'
	]
	success_url = reverse_lazy('bicho_app:correcto')

class ModificarBicho(UpdateView):
	model = Pokemon
	template_name = 'bichos/modificar.html'
	fields = [
		'name',
		'pc',
		'ps',
		'region',
		'tipos'
	]
	success_url = reverse_lazy('bicho_app:correcto')


	def post(self, request, *args, **kwargs):
		self.object = self.get_object()
		return super().post(request, *args, **kwargs)

	def form_valid(self, form):

		return super(ModificarBicho, self).form_valid(form)

class BorrarPokemon(DeleteView):
	template_name = 'bichos/borrar.html'
	model = Pokemon
	context_object_name = 'pokemon'
	success_url = reverse_lazy('bicho_app:correcto')

templates/base.html
<!doctype html>
{% load static %}
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport"
content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
<title>{% block title %} {% endblock title %}</title>
</head>
<body>
{% block body %} {% endblock body %}
<script src="{% static 'js/vendor/jquery.js' %}"></script>
<script src="{% static 'js/vendor/what-input.js' %}"></script>
<script src="{% static 'js/vendor/foundation.min.js' %}"></script>
<script>
$(document).foundation();
</script>
</body>
</html>

templates/bichos/agregar.html
{% extends 'base.html' %}
{% block title %}
 Nuevo Pokemon
{% endblock title %}
{% block body %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Agregar Pokemon</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombre:
                    {{ form.name }}
                </label>
            </div>
            <div class="cell large-6">
                <label>Región:
                    {{ form.region }}
                </label>
            </div>
            <div class="cell large-6">
                <label>PC:
                    {{ form.pc }}
                </label>
            </div>
            <div class="cell large-6">
                <label>PS:
                    {{ form.ps }}
                </label>
            </div>
            <div class="cell large-6">
                <label>Tipo:
                    {{ form.tipos }}
                </label>
            </div>
            <div class="cell large-6">
                <label>Imagen:
                    {{ form.avatar }}
                </label>
            </div>
            <div class="cell">
                <button type="submit" class="success button">Guardar</button>
            </div>
        </form>
    </div>
</div>

{% endblock body %}

templates/bichos/borrar.html
<h1>Eliminar pokemon</h1>
<form method="POST">{% csrf_token %}
    <p>Eliminar {{ pokemon.name }}? </p>
    <button type="submit">Eliminar</button>

</form>

templates/bichos/by_kword.html
<h1>Buscar por región</h1>

<form method="GET">
    {% csrf_token %}
    <input type="text" name="nombre_cargado_usuario" placeholder="ingrese región">
    <button type = "submit"> Buscar </button>
</form>

<h2>Lista bichos</h2>

    {% for e in bichos %}
    <li> {{e}} {{e.region.name}} </li>
    {% empty %}
    <h3>Lista Vacía</h3>
    {% endfor %}

templates/bichos/detalle-pokemon.html
<h1>Detalles de pokemon {{ titulo }}</h1>

{{ pokemon }}

<h3>Todos los datos</h3>
<p>{{ pokemon.name }}</p>
<p>{{ pokemon.region.name }}</p>
<p>{{ empleado.pc }}</p>

templates/bichos/lista-nueva-todos.html
{% extends 'base.html' %}
{% block title %}
 Lista Completa
{% endblock title %}
{% block body %}
{% include "includes/header.html" %}
<div class="grid-container">
	<div class="grid-x">
		<h1>Lista Pokemon</h1>

		<form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
			<div class="cell large-7">
				<input type="text" id="kword" name="kword">
			</div>
			<div class="cell large-2">
				<button type="submit" class="success button">Buscar</button>
			</div>
		</form>

		<div class="cell">
			<table>
				<thead>
				<tr>
					<th width="200">ID</th>
					<th>Nombres</th>
					<th width="150">PC</th>
					<th width="150">Región</th>
					<th width="150">Acción</th>
				</tr>
				</thead>
				<tbody>
					{% for e in object_list %}

						<tr>
							<td>{{ e.id }}</td>
							<td>{{ e.name }}</td>
							<td>{{ e.pc }}</td>
							<td>{{ e.region }}</td>
							<td><a class="button warning" href="{% url 'bicho_app:detallebicho' e.id %}">Ver</a></td>
						</tr>
					{% endfor %}
				</tbody>
			</table>

		</div>
	</div>

	<div class="cell">
		{% if is_paginated %}
		<nav aria-label="Pagination">
			<ul class="pagination">
				{% if page_obj.has_previous %}
				<li class="pagination-previous">
					<a href="?page={{page_obj.previous_page_number}}">Atrás</a>
				</li>
				{% endif %}

				{% for pagina in paginator.page_range %}

				{% ifequal pagina page_obj.number %}
				<li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
				{% else %}
				<li><a href="?page={{pagina}}">{{ pagina }}</a></li>
				{% endifequal %}
				{% endfor %}
				{% if page_obj.has_next %}
				<li class="pagination-next">
					<a href="?page={{page_obj.next_page_number}}">Siguiente</a>
				</li>
				{% endif %}
			</ul>
		</nav>
		{% endif %}
	</div>

</div>
{% endblock body %}



<!--
h1>Lista de todos</h1>

<ul>
	{% for e in object_list %}
		<li> {{ e }} </li>	
	{% endfor %}

</ul>
-->

templates/bichos/lista_region.html
<h1>Lista por región</h1>


<ul>
    {% for e in object_list %}
    <li> {{ e }} </li>
    {% endfor %}

</ul>

templates/bichos/listapokemon.html
{% load static %}

<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>Pokemon lista</title>
</head>
<body>
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text">Bichos</li>
            <li>
                <a href="{% url 'bicho_app:bichosall' %}">Listar</a>
            </li>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
            <li><input type="search" placeholder="Buscar"></li>
            <li><button type="button" class="button">Buscar</button></li>
        </ul>
    </div>
</div>

<div class="grid-container">
	<div class="grid-x">
		<h1>Lista Bichos</h1>

		<form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
			<div class="cell large-7">
				<input type="text" id="kword" name="kword" placeholder="Buscar bicho">
			</div>
			<div class="cell large-2">
				<button type="submit" class="success button">Buscar</button>
			</div>
		</form>

		<div class="cell">
			<table>
				<thead>
				<tr>
					<th width="200">ID</th>
					<th>Pokemon</th>
					<th width="150">Region</th>
					<th width="150">PC</th>
					<th width="150">Acción</th>
				</tr>
				</thead>
				<tbody>
					{% for e in bicho %}

						<tr>
							<td>{{ e.id }}</td>
							<td>{{ e.name }}</td>
							<td>{{ e.region }}</td>
							<td>{{ e.pc }}</td>
							<td><a class="button warning" href="{% url 'bicho_app:detallebicho' e.id %}">Ver</a></td>
						</tr>
					{% endfor %}
				</tbody>
			</table>

		</div>
	</div>

	<div class="cell">
		{% if is_paginated %}
		<nav aria-label="Pagination">
			<ul class="pagination">
				{% if page_obj.has_previous %}
				<li class="pagination-previous">
					<a href="?page={{page_obj.previous_page_number}}">Atrás</a>
				</li>
				{% endif %}

				{% for pagina in paginator.page_range %}
				<li><a href="?page={{pagina}}" aria-label="Page 2">{{ pagina }}</a>
				</li>
				{% endfor %}
				{% if page_obj.has_next %}
				<li class="pagination-next">
					<a href="?page={{page_obj.next_page_number}}">Siguiente</a>
				</li>
				{% endif %}
			</ul>
		</nav>
		{% endif %}
	</div>

</div>
</body>
</html>

templates/bichos/modificar.html
<h1>Modificar datos de bicho</h1>

<form method="POST">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Actualizar</button>

</form>

templates/bichos/success.html
<h3>Cargado</h3>

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text">Pokemon</li>
            <li>
                <a href="{% url 'bicho_app:bichosall' %}">Listar</a>
            </li>
            <li><a href='#'>Regiones</a></li>
            <li><a href='#'>Tipos</a></li>
            <li><a href='#'>Ataques</a></li>

        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
            <li><input type="search" placeholder="Nombre"></li>
            <li><a href="{% url 'bicho_app:agregarbicho' %}" class="button" class="button">Agregar Nuevo</a></li>
        </ul>
    </div>
</div>

templates/inicio.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %} Pagina de inicio de sistema empleados{% endblock titulo %}

{% block body %}

{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x">
    <div class="cell large 5">
      <div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
        <div class="orbit-wrapper">

          <div class="orbit-controls">
            <button class="orbit-previous"><span class="show-for-sr">Anterior</span>&#9664;&#xFE0E;</button>
            <button class="orbit-next"><span class="show-for-sr">Siguiente</span>&#9654;&#xFE0E;</button>
          </div>

          <ul class="orbit-container">
            <li class="is-active orbit-slide">
              <figure class="orbit-figure">
                <img class="orbit-image" src={% static "img/portada1.jpg" %} alt="Space">
                <figcaption class="orbit-caption">Pokemon</figcaption>
              </figure>
            </li>
            <li class="orbit-slide">
              <figure class="orbit-figure">
                <img class="orbit-image" src={% static 'img/portada2.jpg' %} alt="Space">
                <figcaption class="orbit-caption">Pokemon</figcaption>
              </figure>
            </li>
          </ul>
          </div>

        </div>
      </div>   
    </div>
  </div>
</div>

<!--
<div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
    <div class="orbit-wrapper">
      <div class="orbit-controls">
        <button class="orbit-previous"><span class="show-for-sr">Anterior</span>&#9664;&#xFE0E;</button>
        <button class="orbit-next"><span class="show-for-sr">Siguiente</span>&#9654;&#xFE0E;</button>
      </div>
      <ul class="orbit-container">
        <li class="is-active orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src={% static "img/portada1.jpg" %} alt="Space">
            <figcaption class="orbit-caption">Pokemon</figcaption>
          </figure>
        </li>
        <li class="orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src={% static 'img/portada2.jpg' %} alt="Space">
            <figcaption class="orbit-caption">Pokemon</figcaption>
          </figure>
        </li>
      </ul>
    </div>
  </div>

-->

{% endblock body %}